### ISSUE TITLE
'attempted to leave type `std::mem::ManuallyDrop<xlib_xcb::Xlib_xcb>` uninitialized, which is invalid'

### ISSUE THREAD

**Issue by laticoda** [iolivia/imgui-ggez-starter#17]
Hello, i can build i can't run it:
    Finished release [optimized] target(s) in 0.14s
     Running `target/release/imgui-ggez-starter`
thread 'main' panicked at 'attempted to leave type `std::mem::ManuallyDrop<xlib_xcb::Xlib_xcb>` uninitialized, which is invalid', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/mem/mod.rs:661:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: x11_dl::xlib_xcb::Xlib_xcb::open
  15: winit::platform::platform::x11::xdisplay::XConnection::new
  16: std::sync::once::Once::call_once::{{closure}}
  17: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:416
  18: winit::platform::platform::EventsLoop::new_x11
  19: winit::platform::platform::EventsLoop::new
  20: winit::EventsLoop::new
  21: ggez::context::ContextBuilder::build
  22: imgui_ggez_starter::main
  23: std::rt::lang_start::{{closure}}
  24: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  25: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  26: std::panicking::try
             at src/libstd/panicking.rs:274
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  29: main
  30: __libc_start_main
  31: _start

**Comment by laticoda** [comment]
Fixed with editing cargo.toml : star version at all dependencies lines

[dependencies]
ggez = "*"

gfx_core = "*"
gfx_device_gl = "*"

imgui = "*"
imgui-gfx-renderer = "*"

**Comment by qezz** [comment]
Works with

```toml
[dependencies]
ggez = "=0.5.1"

gfx_core = "=0.9.2"
gfx_device_gl = "=0.16.2"

imgui = "0.4"
imgui-gfx-renderer = "0.4"

```

**Important update**: you should probably run `cargo update` to update some dependencies.
